<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {



        DB::table('states')->insert([
            ['id' => 401, 'name' => 'Thakurgaon', 'country_id' => 18],
            ['id' => 402, 'name' => 'Christ Church', 'country_id' => 19],
            ['id' => 403, 'name' => 'Saint Andrew', 'country_id' => 19],
            ['id' => 404, 'name' => 'Saint George', 'country_id' => 19],
            ['id' => 405, 'name' => 'Saint James', 'country_id' => 19],
            ['id' => 406, 'name' => 'Saint John', 'country_id' => 19],
            ['id' => 407, 'name' => 'Saint Joseph', 'country_id' => 19],
            ['id' => 408, 'name' => 'Saint Lucy', 'country_id' => 19],
            ['id' => 409, 'name' => 'Saint Michael', 'country_id' => 19],
            ['id' => 410, 'name' => 'Saint Peter', 'country_id' => 19],
            ['id' => 411, 'name' => 'Saint Philip', 'country_id' => 19],
            ['id' => 412, 'name' => 'Saint Thomas', 'country_id' => 19],
            ['id' => 413, 'name' => 'Brest', 'country_id' => 20],
            ['id' => 414, 'name' => "Homjel'", 'country_id' => 20],
            ['id' => 415, 'name' => 'Hrodna', 'country_id' => 20],
            ['id' => 416, 'name' => 'Mahiljow', 'country_id' => 20],
            ['id' => 417, 'name' => 'Mahilyowskaya Voblasts', 'country_id' => 20],
            ['id' => 418, 'name' => 'Minsk', 'country_id' => 20],
            ['id' => 419, 'name' => "Minskaja Voblasts'", 'country_id' => 20],
            ['id' => 420, 'name' => 'Petrik', 'country_id' => 20],
            ['id' => 421, 'name' => 'Vicebsk', 'country_id' => 20],
            ['id' => 422, 'name' => 'Antwerpen', 'country_id' => 21],
            ['id' => 423, 'name' => 'Berchem', 'country_id' => 21],
            ['id' => 424, 'name' => 'Brabant', 'country_id' => 21],
            ['id' => 425, 'name' => 'Brabant Wallon', 'country_id' => 21],
            ['id' => 426, 'name' => 'Brussel', 'country_id' => 21],
            ['id' => 427, 'name' => 'East Flanders', 'country_id' => 21],
            ['id' => 428, 'name' => 'Hainaut', 'country_id' => 21],
            ['id' => 429, 'name' => 'Liege', 'country_id' => 21],
            ['id' => 430, 'name' => 'Limburg', 'country_id' => 21],
            ['id' => 431, 'name' => 'Luxembourg', 'country_id' => 21],
            ['id' => 432, 'name' => 'Namur', 'country_id' => 21],
            ['id' => 433, 'name' => 'Ontario', 'country_id' => 21],
            ['id' => 434, 'name' => 'Oost-Vlaanderen', 'country_id' => 21],
            ['id' => 435, 'name' => 'Provincie Brabant', 'country_id' => 21],
            ['id' => 436, 'name' => 'Vlaams-Brabant', 'country_id' => 21],
            ['id' => 437, 'name' => 'Wallonne', 'country_id' => 21],
            ['id' => 438, 'name' => 'West-Vlaanderen', 'country_id' => 21],
            ['id' => 439, 'name' => 'Belize', 'country_id' => 22],
            ['id' => 440, 'name' => 'Cayo', 'country_id' => 22],
            ['id' => 441, 'name' => 'Corozal', 'country_id' => 22],
            ['id' => 442, 'name' => 'Orange Walk', 'country_id' => 22],
            ['id' => 443, 'name' => 'Stann Creek', 'country_id' => 22],
            ['id' => 444, 'name' => 'Toledo', 'country_id' => 22],
            ['id' => 445, 'name' => 'Alibori', 'country_id' => 23],
            ['id' => 446, 'name' => 'Atacora', 'country_id' => 23],
            ['id' => 447, 'name' => 'Atlantique', 'country_id' => 23],
            ['id' => 448, 'name' => 'Borgou', 'country_id' => 23],
            ['id' => 449, 'name' => 'Collines', 'country_id' => 23],
            ['id' => 450, 'name' => 'Couffo', 'country_id' => 23],
            ['id' => 451, 'name' => 'Donga', 'country_id' => 23],
            ['id' => 452, 'name' => 'Littoral', 'country_id' => 23],
            ['id' => 453, 'name' => 'Mono', 'country_id' => 23],
            ['id' => 454, 'name' => 'Oueme', 'country_id' => 23],
            ['id' => 455, 'name' => 'Plateau', 'country_id' => 23],
            ['id' => 456, 'name' => 'Zou', 'country_id' => 23],
            ['id' => 457, 'name' => 'Hamilton', 'country_id' => 24],
            ['id' => 458, 'name' => 'Saint George', 'country_id' => 24],
            ['id' => 459, 'name' => 'Bumthang', 'country_id' => 25],
            ['id' => 460, 'name' => 'Chhukha', 'country_id' => 25],
            ['id' => 461, 'name' => 'Chirang', 'country_id' => 25],
            ['id' => 462, 'name' => 'Daga', 'country_id' => 25],
            ['id' => 463, 'name' => 'Geylegphug', 'country_id' => 25],
            ['id' => 464, 'name' => 'Ha', 'country_id' => 25],
            ['id' => 465, 'name' => 'Lhuntshi', 'country_id' => 25],
            ['id' => 466, 'name' => 'Mongar', 'country_id' => 25],
            ['id' => 467, 'name' => 'Pemagatsel', 'country_id' => 25],
            ['id' => 468, 'name' => 'Punakha', 'country_id' => 25],
            ['id' => 469, 'name' => 'Rinpung', 'country_id' => 25],
            ['id' => 470, 'name' => 'Samchi', 'country_id' => 25],
            ['id' => 471, 'name' => 'Samdrup Jongkhar', 'country_id' => 25],
            ['id' => 472, 'name' => 'Shemgang', 'country_id' => 25],
            ['id' => 473, 'name' => 'Tashigang', 'country_id' => 25],
            ['id' => 474, 'name' => 'Timphu', 'country_id' => 25],
            ['id' => 475, 'name' => 'Tongsa', 'country_id' => 25],
            ['id' => 476, 'name' => 'Wangdiphodrang', 'country_id' => 25],
            ['id' => 477, 'name' => 'Beni', 'country_id' => 26],
            ['id' => 478, 'name' => 'Chuquisaca', 'country_id' => 26],
            ['id' => 479, 'name' => 'Cochabamba', 'country_id' => 26],
            ['id' => 480, 'name' => 'La Paz', 'country_id' => 26],
            ['id' => 481, 'name' => 'Oruro', 'country_id' => 26],
            ['id' => 482, 'name' => 'Pando', 'country_id' => 26],
            ['id' => 483, 'name' => 'Potosi', 'country_id' => 26],
            ['id' => 484, 'name' => 'Santa Cruz', 'country_id' => 26],
            ['id' => 485, 'name' => 'Tarija', 'country_id' => 26],
            ['id' => 486, 'name' => 'Federacija Bosna i Hercegovina', 'country_id' => 27],
            ['id' => 487, 'name' => 'Republika Srpska', 'country_id' => 27],
            ['id' => 488, 'name' => 'Central Bobonong', 'country_id' => 28],
            ['id' => 489, 'name' => 'Central Boteti', 'country_id' => 28],
            ['id' => 490, 'name' => 'Central Mahalapye', 'country_id' => 28],
            ['id' => 491, 'name' => 'Central Serowe-Palapye', 'country_id' => 28],
            ['id' => 492, 'name' => 'Central Tutume', 'country_id' => 28],
            ['id' => 493, 'name' => 'Chobe', 'country_id' => 28],
            ['id' => 494, 'name' => 'Francistown', 'country_id' => 28],
            ['id' => 495, 'name' => 'Gaborone', 'country_id' => 28],
            ['id' => 496, 'name' => 'Ghanzi', 'country_id' => 28],
            ['id' => 497, 'name' => 'Jwaneng', 'country_id' => 28],
            ['id' => 498, 'name' => 'Kgalagadi North', 'country_id' => 28],
            ['id' => 499, 'name' => 'Kgalagadi South', 'country_id' => 28],
            ['id' => 500, 'name' => 'Kgatleng', 'country_id' => 28],
            ['id' => 501, 'name' => 'Kweneng', 'country_id' => 28],
            ['id' => 502, 'name' => 'Lobatse', 'country_id' => 28],
            ['id' => 503, 'name' => 'Ngamiland', 'country_id' => 28],
            ['id' => 504, 'name' => 'Ngwaketse', 'country_id' => 28],
            ['id' => 505, 'name' => 'North East', 'country_id' => 28],
            ['id' => 506, 'name' => 'Okavango', 'country_id' => 28],
            ['id' => 507, 'name' => 'Orapa', 'country_id' => 28],
            ['id' => 508, 'name' => 'Selibe Phikwe', 'country_id' => 28],
            ['id' => 509, 'name' => 'South East', 'country_id' => 28],
            ['id' => 510, 'name' => 'Sowa', 'country_id' => 28],
            ['id' => 511, 'name' => 'Bouvet Island', 'country_id' => 29],
            ['id' => 512, 'name' => 'Acre', 'country_id' => 30],
            ['id' => 513, 'name' => 'Alagoas', 'country_id' => 30],
            ['id' => 514, 'name' => 'Amapa', 'country_id' => 30],
            ['id' => 515, 'name' => 'Amazonas', 'country_id' => 30],
            ['id' => 516, 'name' => 'Bahia', 'country_id' => 30],
            ['id' => 517, 'name' => 'Ceara', 'country_id' => 30],
            ['id' => 518, 'name' => 'Distrito Federal', 'country_id' => 30],
            ['id' => 519, 'name' => 'Espirito Santo', 'country_id' => 30],
            ['id' => 520, 'name' => 'Estado de Sao Paulo', 'country_id' => 30],
            ['id' => 521, 'name' => 'Goias', 'country_id' => 30],
            ['id' => 522, 'name' => 'Maranhao', 'country_id' => 30],
            ['id' => 523, 'name' => 'Mato Grosso', 'country_id' => 30],
            ['id' => 524, 'name' => 'Mato Grosso do Sul', 'country_id' => 30],
            ['id' => 525, 'name' => 'Minas Gerais', 'country_id' => 30],
            ['id' => 526, 'name' => 'Para', 'country_id' => 30],
            ['id' => 527, 'name' => 'Paraiba', 'country_id' => 30],
            ['id' => 528, 'name' => 'Parana', 'country_id' => 30],
            ['id' => 529, 'name' => 'Pernambuco', 'country_id' => 30],
            ['id' => 530, 'name' => 'Piaui', 'country_id' => 30],
            ['id' => 531, 'name' => 'Rio Grande do Norte', 'country_id' => 30],
            ['id' => 532, 'name' => 'Rio Grande do Sul', 'country_id' => 30],
            ['id' => 533, 'name' => 'Rio de Janeiro', 'country_id' => 30],
            ['id' => 534, 'name' => 'Rondonia', 'country_id' => 30],
            ['id' => 535, 'name' => 'Roraima', 'country_id' => 30],
            ['id' => 536, 'name' => 'Santa Catarina', 'country_id' => 30],
            ['id' => 537, 'name' => 'Sao Paulo', 'country_id' => 30],
            ['id' => 538, 'name' => 'Sergipe', 'country_id' => 30],
            ['id' => 539, 'name' => 'Tocantins', 'country_id' => 30],
            ['id' => 540, 'name' => 'British Indian Ocean Territory', 'country_id' => 31],
            ['id' => 541, 'name' => 'Belait', 'country_id' => 32],
            ['id' => 542, 'name' => 'Brunei-Muara', 'country_id' => 32],
            ['id' => 543, 'name' => 'Temburong', 'country_id' => 32],
            ['id' => 544, 'name' => 'Tutong', 'country_id' => 32],
            ['id' => 545, 'name' => 'Blagoevgrad', 'country_id' => 33],
            ['id' => 546, 'name' => 'Burgas', 'country_id' => 33],
            ['id' => 547, 'name' => 'Dobrich', 'country_id' => 33],
        ]);
    }
}
