<?php

namespace App\Services;

use App\Models\ManageEmailsContent;

class ManageEmailsContentService
{
    /**
     * @return array<int, array<string, mixed>>
     */
    public static function defaultTemplates(): array
    {
        return [
            ['email_slug' => 'register_admin', 'email_type' => 'Registration Email For Admin', 'email_subject' => 'Team Cabinet - New User Registered.', 'email_content' => '<p>Hello Admin,</p><p>New user registered with Team Cabinet Distributors.</p><p>Please check in the portal for more details.</p><p>TEAM</p>', 'macro' => '', 'email_from' => 0],
            ['email_slug' => 'register_user', 'email_type' => 'Registration Email For User', 'email_subject' => 'Team Cabinet - Thanks For Registering With Us.', 'email_content' => '<p>Dear {USERNAME},</p><p>Thanks for registering as a member of TEAM CABINET DISTRIBUTORS, LLC</p><p>You will get confirmation email once your account has been approved by admin.</p><p>Stay connected with us for best deals!!</p><p>TEAM</p>', 'macro' => '{USERNAME}', 'email_from' => 0],
            ['email_slug' => 'forgot_password_user', 'email_type' => 'Forgot Password Email', 'email_subject' => 'Team Cabinet - New Password Generated.', 'email_content' => '<p>Dear {USERNAME},</p><p>Someone has requested a change password for your Team Cabinet account.</p><p>Your new password is <strong>{PASSWORD}</strong></p><p>If it is not requested by you, please ignore this email.</p><p>TEAM</p>', 'macro' => '{USERNAME},{PASSWORD}', 'email_from' => 0],
            ['email_slug' => 'reset_password_link', 'email_type' => 'Reset Password Link Email', 'email_subject' => 'Team Cabinet - Reset Your Password', 'email_content' => '<p>Dear {USERNAME},</p><p>We received a request to reset your password.</p><p style="text-align:center;margin:24px 0;"><a href="{RESET_LINK}" style="display:inline-block;padding:10px 20px;background:#398ebd;color:#fff;text-decoration:none;border-radius:4px;">Reset password</a></p><p>This link expires in 60 minutes. If you did not request this, ignore this email.</p><p>TEAM</p>', 'macro' => '{USERNAME},{RESET_LINK}', 'email_from' => 0],
            ['email_slug' => 'login_otp', 'email_type' => 'Login OTP Email', 'email_subject' => 'Team Cabinet - Your Login Code', 'email_content' => '<p>Dear {USERNAME},</p><p>Use this one-time code to sign in:</p><p style="text-align:center;font-size:28px;font-weight:bold;letter-spacing:6px;color:#0c2340;">{OTP}</p><p style="font-size:14px;color:#64748b;">This code expires in 10 minutes.</p><p>TEAM</p>', 'macro' => '{USERNAME},{OTP}', 'email_from' => 0],
            ['email_slug' => 'forgot_username', 'email_type' => 'Forgot Username Email', 'email_subject' => 'Team Cabinet - Your Username', 'email_content' => '<p>Dear {USERNAME},</p><p>Your username is: <strong>{LOGIN}</strong></p><p><a href="{LOGIN_URL}">Sign in here</a></p><p>TEAM</p>', 'macro' => '{USERNAME},{LOGIN},{LOGIN_URL}', 'email_from' => 0],
            ['email_slug' => 'password_changed', 'email_type' => 'Password Changed Email', 'email_subject' => 'Team Cabinet - Password Changed', 'email_content' => '<p>Dear {USERNAME},</p><p>Your password was changed successfully. If you did not make this change, contact support immediately.</p><p>TEAM</p>', 'macro' => '{USERNAME}', 'email_from' => 0],
            ['email_slug' => 'tenant_registered', 'email_type' => 'Tenant Registered Welcome', 'email_subject' => 'Welcome to Pinnacle System', 'email_content' => '<p>Dear {USERNAME},</p><p>Your tenant account has been created.</p><p><a href="{LOGIN_URL}">Sign in to your panel</a></p><p>TEAM</p>', 'macro' => '{USERNAME},{LOGIN_URL}', 'email_from' => 0],
            ['email_slug' => 'user_status', 'email_type' => 'User Status Email', 'email_subject' => 'Team Cabinet - Your Account Is Approved.', 'email_content' => '<p>Dear {USERNAME},</p><p>Your account has been approved by admin.</p><p>Now you can login to the portal with your username and password.</p><p>Team,<br>Team Cabinet</p>', 'macro' => '{USERNAME}', 'email_from' => 0],
            ['email_slug' => 'user_deactivated', 'email_type' => 'User Deactivated Email', 'email_subject' => 'Team Cabinet - Your Account Has Been Deactivated.', 'email_content' => '<p>Dear {USERNAME},</p><p>Your account has been deactivated by admin. Contact support if you have questions.</p><p>Team,<br>Team Cabinet</p>', 'macro' => '{USERNAME}', 'email_from' => 0],
            ['email_slug' => 'order_email_to_user', 'email_type' => 'Order Email For User', 'email_subject' => 'Team Cabinet - Your Order Placed Successfully(Order #: {INVOICE}).', 'email_content' => '<p>Dear {USERNAME},</p><p>Thank you for placing an order with Team Cabinet. Please find below the order details:</p><p>Order #: {INVOICE}</p><p>{CONTENT}</p><p>TEAM</p>', 'macro' => '{USERNAME},{CONTENT},{INVOICE}', 'email_from' => 0],
            ['email_slug' => 'order_email_to_admin', 'email_type' => 'Order Email For Admin', 'email_subject' => 'Team Cabinet - New Order Placed(Order #: {INVOICE}).', 'email_content' => '<p>Hello Admin,</p><p>{USERNAME} has placed a new order. Order #: {INVOICE}</p><p>{CONTENT}</p><p>Team Cabinet</p>', 'macro' => '{USERNAME},{CONTENT},{INVOICE}', 'email_from' => 0],
            ['email_slug' => 'order_email_to_warehouse', 'email_type' => 'Order Email For Warehouse', 'email_subject' => 'Team Cabinet - New Order Placed (Order #: {INVOICE}).', 'email_content' => '<p>Order #: {INVOICE}</p><p>{CONTENT}</p>', 'macro' => '{CONTENT},{INVOICE}', 'email_from' => 0],
            ['email_slug' => 'order_status_to_user', 'email_type' => 'Order Status Email', 'email_subject' => 'Team Cabinet - Your Order Status Is Changed.', 'email_content' => '<p>Dear {USERNAME},</p><p>Your order status is {STATUS}.</p><p>Invoice: {INVOICE}</p><p>Team Cabinet</p>', 'macro' => '{STATUS},{USERNAME},{INVOICE}', 'email_from' => 0],
            ['email_slug' => 'claim_email_to_admin', 'email_type' => 'Claim Email For Admin', 'email_subject' => 'Team Cabinet - Order Claim Request Submitted By User.', 'email_content' => '<p>Hello Admin,</p><p>New claim request from {USERNAME}:</p><p>{CONTENT}</p><p>Team Cabinet</p>', 'macro' => '{USERNAME},{CONTENT}', 'email_from' => 0],
            ['email_slug' => 'claim_email_to_user', 'email_type' => 'Claim Email For User', 'email_subject' => 'Team Cabinet - Your Order Claim Request Submitted Successfully.', 'email_content' => '<p>Dear {USERNAME},</p><p>Your claim request has been sent successfully:</p><p>{CONTENT}</p><p>Team Cabinet</p>', 'macro' => '{USERNAME},{CONTENT}', 'email_from' => 0],
            ['email_slug' => 'affiliate_register_to_user', 'email_type' => 'Registration Email For Affiliates', 'email_subject' => 'Team Cabinet - Your Account Is Created.', 'email_content' => '<p>Dear {USERNAME},</p><p>Your account was created by <strong>{PARENT_USER}</strong>.</p><p><strong>Site URL:</strong> {URL}</p><p><strong>Username:</strong> {USERNAME}</p><p><strong>Password:</strong> {PASSWORD}</p><p>Team Cabinet</p>', 'macro' => '{PARENT_USER},{URL},{USERNAME},{PASSWORD}', 'email_from' => 0],
            ['email_slug' => 'order_email_to_rep', 'email_type' => 'Order Email For Representative', 'email_subject' => 'Team Cabinet - New Order Placed By Your Customer.', 'email_content' => '<p>Dear {REPRESENTATIVE},</p><p>{USERNAME} has placed a new order:</p><p>{CONTENT}</p><p>Team Cabinet</p>', 'macro' => '{USERNAME},{CONTENT},{REPRESENTATIVE}', 'email_from' => 0],
            ['email_slug' => 'user_reg_by_admin', 'email_type' => 'Registration Email For User (Registered By Admin)', 'email_subject' => 'Your dealer account has been created', 'email_content' => '<p>Thank you for being part of our TEAM.</p><p>Your dealer account was created by an administrator. Use the details below to sign in.</p><p><strong>Sign-in link:</strong> <a href="{URL}">{URL}</a></p><p><strong>Username:</strong> {USERNAME}</p><p><strong>Password:</strong> {PASSWORD}</p><p>We recommend changing your password after your first login.</p><p>Team Cabinets</p>', 'macro' => '{USERNAME},{PASSWORD},{URL}', 'email_from' => 0],
            ['email_slug' => 'contact_us', 'email_type' => 'Contact Us Email For Admin', 'email_subject' => 'Team Cabinet - Contact Us Submission.', 'email_content' => '<p>Hello Admin,</p><p><strong>Name:</strong> {USERNAME}</p><p><strong>Email:</strong> {EMAIL}</p><p><strong>Message:</strong> {QUERY}</p><p>Team Cabinet</p>', 'macro' => '{USERNAME},{EMAIL},{QUERY}', 'email_from' => 0],
            ['email_slug' => 'user_query_to_admin', 'email_type' => 'User Query Email For Admin', 'email_subject' => 'Team Cabinet - New Order Query Submitted By User.', 'email_content' => '<p>Hello Admin,</p><p><strong>Username:</strong> {USERNAME}</p><p><strong>Email:</strong> {EMAIL}</p><p><strong>Subject:</strong> {SUBJECT}</p><p><strong>Query:</strong> {QUERY}</p><p>Team Cabinet</p>', 'macro' => '{USERNAME},{EMAIL},{SUBJECT},{QUERY}', 'email_from' => 0],
            ['email_slug' => 'shipping_quote_req_to_admin', 'email_type' => 'Shipping Quote Email For Admin', 'email_subject' => 'Team Cabinets - New Shipping Quote Request', 'email_content' => '<p>Hello Admin,</p><p>{USERNAME} requested a shipping quote:</p><p>{CONTENT}</p><p>Team Cabinets</p>', 'macro' => '{USERNAME},{CONTENT}', 'email_from' => 0],
            ['email_slug' => 'shipping_quote_req_to_user', 'email_type' => 'Shipping Quote Email For User', 'email_subject' => 'Team Cabinets - Your Shipping Quote Updated By Admin', 'email_content' => '<p>Dear {USERNAME},</p><p>Your shipping quote has been updated:</p><p>{CONTENT}</p><p>Team Cabinets</p>', 'macro' => '{USERNAME},{CONTENT}', 'email_from' => 0],
            ['email_slug' => 'stock_check_req_to_admin', 'email_type' => 'Stock Check Email For Admin', 'email_subject' => 'Team Cabinets - New Stock Check Request', 'email_content' => '<p>Hello Admin,</p><p>{USERNAME} requested a stock check:</p><p>{CONTENT}</p><p>Team Cabinets</p>', 'macro' => '{USERNAME},{CONTENT}', 'email_from' => 0],
            ['email_slug' => 'stock_check_req_to_user', 'email_type' => 'Stock Check Email For User', 'email_subject' => 'Team Cabinets - Your Stock Check Request Approved By Admin', 'email_content' => '<p>Dear {USERNAME},</p><p>Your stock check request has been approved:</p><p>{CONTENT}</p><p>Team Cabinets</p>', 'macro' => '{USERNAME},{CONTENT}', 'email_from' => 0],
            ['email_slug' => 'stock_check_req_to_warehouse', 'email_type' => 'Stock Check Email For Warehouse', 'email_subject' => 'Team Cabinets - New Stock Check Request # : {ID}', 'email_content' => '<p>Hello Warehouse,</p><p>Stock check request details:</p><p>{CONTENT}</p><p>Team Cabinets</p>', 'macro' => '{CONTENT},{ID}', 'email_from' => 0],
            ['email_slug' => 'update_stock_check_req_to_admin', 'email_type' => 'Update Stock Check Email For Admin', 'email_subject' => 'Team Cabinets - Updated Stock Check Request', 'email_content' => '<p>Hello Admin,</p><p>{USERNAME} updated stock check #{STOCK_CHECK_ID}:</p><p>{CONTENT}</p><p>Team Cabinets</p>', 'macro' => '{USERNAME},{CONTENT},{STOCK_CHECK_ID}', 'email_from' => 0],
        ];
    }

    public function ensureDefaults(): void
    {
        foreach (self::defaultTemplates() as $row) {
            ManageEmailsContent::query()->updateOrCreate(
                ['email_slug' => $row['email_slug']],
                $row
            );
        }
    }
}
