<?php

/**
 * Florida county sales tax rates (legacy CI sales_tax_counties, state_id = 9).
 */
return [
    'state_id' => 9,
    'counties' => [
        ['counties' => 'Alachua County', 'tax' => 7.51],
        ['counties' => 'Baker County', 'tax' => 7],
        ['counties' => 'Bay County', 'tax' => 7],
        ['counties' => 'Bradford County', 'tax' => 7],
        ['counties' => 'Brevard County', 'tax' => 7],
        ['counties' => 'Broward County', 'tax' => 7],
        ['counties' => 'Calhoun County', 'tax' => 7.5],
        ['counties' => 'Charlotte County', 'tax' => 7],
        ['counties' => 'Citrus County', 'tax' => 6],
        ['counties' => 'Clay County', 'tax' => 7.5],
        ['counties' => 'Collier County', 'tax' => 7],
        ['counties' => 'Columbia County', 'tax' => 7.5],
        ['counties' => 'DeSoto County', 'tax' => 7.5],
        ['counties' => 'Dixie County', 'tax' => 7],
        ['counties' => 'Duval County', 'tax' => 7.5],
        ['counties' => 'Escambia County', 'tax' => 7.5],
        ['counties' => 'Flagler County', 'tax' => 7],
        ['counties' => 'Franklin County', 'tax' => 7.5],
        ['counties' => 'Gadsden County', 'tax' => 7.5],
        ['counties' => 'Gilchrist County', 'tax' => 7],
        ['counties' => 'Glades County', 'tax' => 7],
        ['counties' => 'Gulf County', 'tax' => 7],
        ['counties' => 'Hamilton County', 'tax' => 7],
        ['counties' => 'Hardee County', 'tax' => 7],
        ['counties' => 'Hendry County', 'tax' => 7.5],
        ['counties' => 'Hernando County', 'tax' => 6.5],
        ['counties' => 'Highlands County', 'tax' => 7.5],
        ['counties' => 'Hillsborough County', 'tax' => 7.5],
        ['counties' => 'Holmes County', 'tax' => 7.5],
        ['counties' => 'Indian River County', 'tax' => 7],
        ['counties' => 'Jackson County', 'tax' => 7.5],
        ['counties' => 'Jefferson County', 'tax' => 7],
        ['counties' => 'Lafayette County', 'tax' => 7],
        ['counties' => 'Lake County', 'tax' => 7],
        ['counties' => 'Lee County', 'tax' => 6.5],
        ['counties' => 'Leon County', 'tax' => 7.5],
        ['counties' => 'Levy County', 'tax' => 7],
        ['counties' => 'Liberty County', 'tax' => 7.5],
        ['counties' => 'Madison County', 'tax' => 7.5],
        ['counties' => 'Manatee County', 'tax' => 7],
        ['counties' => 'Marion County', 'tax' => 7],
        ['counties' => 'Martin County', 'tax' => 6.5],
        ['counties' => 'Miami-Dade County', 'tax' => 7],
        ['counties' => 'Monroe County', 'tax' => 7.5],
        ['counties' => 'Nassau County', 'tax' => 7],
        ['counties' => 'Okaloosa County', 'tax' => 7],
        ['counties' => 'Okeechobee County', 'tax' => 7],
        ['counties' => 'Orange County', 'tax' => 6.5],
        ['counties' => 'Osceola County', 'tax' => 7.5],
        ['counties' => 'Palm Beach County', 'tax' => 7],
        ['counties' => 'Pasco County', 'tax' => 7],
        ['counties' => 'Pinellas County', 'tax' => 7],
        ['counties' => 'Polk County', 'tax' => 7],
        ['counties' => 'Putnam County', 'tax' => 7],
        ['counties' => 'Santa Rosa County', 'tax' => 7],
        ['counties' => 'Sarasota County', 'tax' => 7],
        ['counties' => 'Seminole County', 'tax' => 7],
        ['counties' => 'St. Johns County', 'tax' => 6.5],
        ['counties' => 'St. Lucie County', 'tax' => 7],
        ['counties' => 'Sumter County', 'tax' => 7],
        ['counties' => 'Suwannee County', 'tax' => 7],
        ['counties' => 'Taylor County', 'tax' => 7],
        ['counties' => 'Union County', 'tax' => 7],
        ['counties' => 'Volusia County', 'tax' => 6.5],
        ['counties' => 'Wakulla County', 'tax' => 7.5],
        ['counties' => 'Walton County', 'tax' => 7],
        ['counties' => 'Washington County', 'tax' => 7.5],
    ],
];
