<?php

return [
    'sections' => [
        [
            'label' => 'My Profile',
            'route' => 'tenant_setting_profile',
            'icon' => 'user',
            'active' => [
                'tenant_setting_profile',
                'tenant_setting_profile_update',
                'tenant_setting_profile_password',
            ],
        ],
        [
            'label' => 'Menu Layout',
            'route' => 'tenant_nav_menu_edit',
            'icon' => 'sliders',
            'panel_admin_only' => true,
            'active' => [
                'tenant_nav_menu_edit',
                'tenant_nav_menu_update',
                'tenant_nav_menu_reset',
            ],
        ],
        [
            'label' => 'Site Settings',
            'route' => 'tenant_site_setting',
            'active' => ['tenant_site_setting', 'tenant_site_settings_store'],
        ],
        [
            'label' => 'Website Designing',
            'route' => 'tenant_website_designing',
            'icon' => 'monitor',
            'active' => [
                'tenant_website_designing',
                'tenant_frontend_theme',
                'tenant_frontend_theme_store',
                'tenant_home_setting_index',
                'tenant_home_setting_srore',
                'pages.create',
                'pages.index',
                'pages.edit',
                'pages.show',
                'pages.store',
                'pages.update',
                'pages.destroy',
                'tenant_setting_manage_index',
                'tenant_setting_manage_contact_*',
                'tenant_storefront_about',
                'tenant_storefront_blog',
                'tenant_setting_manage_create',
                'tenant_setting_manage_about_*',
            ],
        ],
        [
            'label' => 'Tax & Fees',
            'route' => 'tenant_setting_tax_fees',
            'active' => [
                'tenant_setting_tax_fees',
                'tenant_setting_tax_fees_payment',
                'tenant_setting_tax_fees_payment_store',
                'tenant_setting_tax_fees_shipping',
                'tenant_setting_tax_fees_shipping_store',
                'tenant_setting_tax_fees_paytrace',
                'tenant_setting_tax_fees_paytrace_store',
                'tenant_setting_tax_fees_store',
                'tenant_setting_manage_credit',
                'tenant_setting_manage_fuel',
            ],
        ],
        [
            'label' => 'Sales Tax Management',
            'route' => 'tenant_setting_tax_fees_sales_tax',
            'icon' => 'map-pin',
            'active' => [
                'tenant_setting_tax_fees_sales_tax',
                'tenant_setting_tax_fees_sales_tax_edit',
                'tenant_setting_tax_fees_sales_tax_update',
                'tenant_setting_tax_fees_sales_tax_store',
            ],
        ],
        [
            'label' => 'Commission & Point Factors',
            'route' => 'tenant_setting_commission',
            'active' => ['tenant_setting_commission'],
        ],
        [
            'label' => 'QuickBooks',
            'route' => 'tenant_quickbooks_index',
            'active' => ['tenant_quickbooks_*'],
        ],
        [
            'label' => 'Roles & Permissions',
            'route' => 'tenant_role_index',
            'active' => ['tenant_role_*', 'role.export', 'role.import'],
        ],
        [
            'label' => 'Email Settings',
            'route' => 'tenant_setting_email_settings',
            'active' => [
                'tenant_setting_email_settings',
                'tenant_email_settings_api_*',
                'tenant_setting_manage_stmp',
                'tenant_setting_manage_stmp_*',
                'tenant_setting_manage_email_content',
                'tenant_setting_manage_email_content_*',
            ],
        ],
        [
            'label' => 'Success / Error Messages',
            'route' => 'tenant_setting_manage_success_list',
            'active' => ['tenant_setting_manage_success', 'tenant_setting_manage_success_*'],
        ],
        [
            'label' => 'Documentation',
            'route' => 'tenant_setting_manage_documentation_list',
            'icon' => 'book-open',
            'panel_admin_only' => true,
            'active' => [
                'tenant_setting_manage_document',
                'tenant_setting_manage_documentation_*',
                'tenant_deleted_manage_document_list',
                'tenant_manage_documents_api_*',
            ],
        ],
        [
            'label' => 'Admin File Uploads',
            'route' => 'tenant_admin_uploads_index',
            'icon' => 'upload',
            'panel_admin_only' => true,
            'active' => ['tenant_admin_uploads_*'],
        ],
        [
            'label' => 'Inventory Admin',
            'route' => 'tenant_inventory_admin_index',
            'icon' => 'package',
            'panel_admin_only' => true,
            'active' => ['tenant_inventory_admin_*'],
        ],
    ],

    'settings_chrome_routes' => [
        'tenant_settings_hub',
        'tenant_setting_profile',
        'tenant_setting_profile_update',
        'tenant_setting_profile_password',
        'tenant_nav_menu_*',
        'tenant_site_setting',
        'tenant_site_settings_store',
        'tenant_website_designing',
        'tenant_frontend_theme',
        'tenant_frontend_theme_store',
        'tenant_home_setting_index',
        'tenant_home_setting_srore',
        'pages.create',
        'pages.index',
        'pages.edit',
        'pages.show',
        'pages.store',
        'pages.update',
        'pages.destroy',
        'tenant_setting_tax_fees',
        'tenant_setting_tax_fees_payment',
        'tenant_setting_tax_fees_payment_store',
        'tenant_setting_tax_fees_shipping',
        'tenant_setting_tax_fees_shipping_store',
        'tenant_setting_tax_fees_sales_tax',
        'tenant_setting_tax_fees_sales_tax_store',
        'tenant_setting_tax_fees_paytrace',
        'tenant_setting_tax_fees_paytrace_store',
        'tenant_setting_tax_fees_store',
        'tenant_setting_commission',
        'tenant_setting_email_settings',
        'tenant_email_settings_api_*',
        'tenant_setting_manage_stmp',
        'tenant_setting_manage_stmp_*',
        'tenant_setting_manage_email_content',
        'tenant_setting_manage_email_content_*',
        'tenant_setting_manage_success',
        'tenant_setting_manage_success_*',
        'tenant_setting_manage_index',
        'tenant_setting_manage_contact_*',
        'tenant_contact_page_settings',
        'tenant_contact_page_settings_store',
        'tenant_legal_pages',
        'tenant_legal_pages_edit',
        'tenant_legal_pages_update',
        'tenant_contact_queries_*',
        'tenant_setting_manage_create',
        'tenant_setting_manage_about_*',
        'tenant_quickbooks_*',
        'tenant_role_*',
        'role.export',
        'role.import',
        'tenant_setting_manage_document',
        'tenant_setting_manage_documentation_*',
        'tenant_deleted_manage_document_list',
        'tenant_manage_documents_api_*',
        'tenant_admin_uploads_*',
        'tenant_inventory_admin_*',
        'tenant_dashboard_catalog_sales',
    ],
];
