<?php

return [
    'sections' => [
        [
            'label' => 'Site Settings',
            'route' => 'tenant_site_setting',
            'active' => ['tenant_site_setting', 'tenant_site_settings_store'],
        ],
        [
            'label' => 'Website Designing',
            'route' => 'tenant_website_designing',
            'icon' => 'monitor',
            'active' => [
                'tenant_website_designing',
                'tenant_frontend_theme',
                'tenant_frontend_theme_store',
                'tenant_home_setting_index',
                'tenant_home_setting_srore',
                'pages.create',
                'pages.index',
                'pages.edit',
                'pages.show',
                'pages.store',
                'pages.update',
                'pages.destroy',
                'tenant_setting_manage_index',
                'tenant_setting_manage_contact_*',
                'tenant_storefront_about',
                'tenant_storefront_blog',
                'tenant_setting_manage_create',
                'tenant_setting_manage_about_*',
            ],
        ],
        [
            'label' => 'Tax & Fees',
            'route' => 'tenant_setting_tax_fees',
            'active' => [
                'tenant_setting_tax_fees',
                'tenant_setting_tax_fees_payment',
                'tenant_setting_tax_fees_payment_store',
                'tenant_setting_tax_fees_shipping',
                'tenant_setting_tax_fees_shipping_store',
                'tenant_setting_tax_fees_sales_tax',
                'tenant_setting_tax_fees_sales_tax_store',
                'tenant_setting_tax_fees_paytrace',
                'tenant_setting_tax_fees_paytrace_store',
                'tenant_setting_tax_fees_store',
                'tenant_setting_manage_credit',
                'tenant_setting_manage_fuel',
            ],
        ],
        [
            'label' => 'Commission & Point Factors',
            'route' => 'tenant_setting_commission',
            'active' => ['tenant_setting_commission'],
        ],
        [
            'label' => 'QuickBooks',
            'route' => 'tenant_quickbooks_index',
            'active' => ['tenant_quickbooks_*'],
        ],
        [
            'label' => 'Roles & Permissions',
            'route' => 'tenant_role_index',
            'active' => ['tenant_role_*', 'role.export', 'role.import'],
        ],
        [
            'label' => 'SMTP Settings',
            'route' => 'tenant_setting_manage_stmp',
            'active' => ['tenant_setting_manage_stmp', 'tenant_setting_manage_stmp_*'],
        ],
        [
            'label' => 'Email Content',
            'route' => 'tenant_setting_manage_email_content',
            'active' => ['tenant_setting_manage_email_content', 'tenant_setting_manage_email_content_*'],
        ],
        [
            'label' => 'Success / Error Messages',
            'route' => 'tenant_setting_manage_success_list',
            'active' => ['tenant_setting_manage_success', 'tenant_setting_manage_success_*'],
        ],
    ],

    'settings_chrome_routes' => [
        'tenant_settings_hub',
        'tenant_site_setting',
        'tenant_site_settings_store',
        'tenant_website_designing',
        'tenant_frontend_theme',
        'tenant_frontend_theme_store',
        'tenant_home_setting_index',
        'tenant_home_setting_srore',
        'pages.create',
        'pages.index',
        'pages.edit',
        'pages.show',
        'pages.store',
        'pages.update',
        'pages.destroy',
        'tenant_setting_tax_fees',
        'tenant_setting_tax_fees_payment',
        'tenant_setting_tax_fees_payment_store',
        'tenant_setting_tax_fees_shipping',
        'tenant_setting_tax_fees_shipping_store',
        'tenant_setting_tax_fees_sales_tax',
        'tenant_setting_tax_fees_sales_tax_store',
        'tenant_setting_tax_fees_paytrace',
        'tenant_setting_tax_fees_paytrace_store',
        'tenant_setting_tax_fees_store',
        'tenant_setting_commission',
        'tenant_setting_manage_stmp',
        'tenant_setting_manage_stmp_*',
        'tenant_setting_manage_email_content',
        'tenant_setting_manage_email_content_*',
        'tenant_setting_manage_success',
        'tenant_setting_manage_success_*',
        'tenant_setting_manage_index',
        'tenant_setting_manage_contact_*',
        'tenant_setting_manage_create',
        'tenant_setting_manage_about_*',
        'tenant_quickbooks_*',
        'tenant_role_*',
        'role.export',
        'role.import',
    ],
];
